name: Piezas de Ajedrez
rules:
  - image: casilleroVacio.png
    when:
      black: 10
      blue: 0
      green: 0
      red: 0
  - image: casilleroDespuesDeMover.png
    when:
      black: 11
      blue: 0
      green: 0
      red: 0
  - image: peonN.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: torreN.png
    when:
      black: 4
      blue: 0
      green: 0
      red: 0
  - image: caballoN.png
    when:
      black: 3
      blue: 0
      green: 0
      red: 0
  - image: alfilN.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 0
  - image: reyN.png
    when:
      black: 6
      blue: 0
      green: 0
      red: 0
  - image: reinaN.png
    when:
      black: 5
      blue: 0
      green: 0
      red: 0
  - image: peonB.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 1
  - image: torreB.png
    when:
      black: 0
      blue: 4
      green: 0
      red: 1
  - image: caballoB.png
    when:
      black: 0
      blue: 3
      green: 0
      red: 1
  - image: alfilB.png
    when:
      black: 0
      blue: 2
      green: 0
      red: 1
  - image: reyB.png
    when:
      black: 0
      blue: 6
      green: 0
      red: 1
  - image: reinaB.png
    when:
      black: 0
      blue: 5
      green: 0
      red: 1
    - image: peonNSeleccionado.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 1
  - image: torreNSeleccionado.png
    when:
      black: 4
      blue: 0
      green: 0
      red: 1
  - image: caballoNSeleccionado.png
    when:
      black: 3
      blue: 0
      green: 0
      red: 1
  - image: alfilNSeleccionado.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 1
  - image: reyNSeleccionado.png
    when:
      black: 6
      blue: 0
      green: 0
      red: 1
  - image: reinaNSeleccionado.png
    when:
      black: 5
      blue: 0
      green: 0
      red: 1
  - image: peonBSeleccionado.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 1
  - image: torreBSeleccionado.png
    when:
      black: 0
      blue: 4
      green: 0
      red: 1
  - image: caballoBSeleccionado.png
    when:
      black: 0
      blue: 3
      green: 0
      red: 1
  - image: alfilBSeleccionado.png
    when:
      black: 0
      blue: 2
      green: 0
      red: 1
  - image: reyBSeleccionado.png
    when:
      black: 0
      blue: 6
      green: 0
      red: 1
  - image: reinaBSeleccionado.png
    when:
      black: 0
      blue: 5
      green: 0
      red: 1